config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post '/categories/:category_id/papers/:id/read' ,to:'papers#read_status'
  resources :categories do
    resources :papers do
      resources :comments, only: :create do
        resources :student_comment_ratings
      end
      resources :genres_papers, only: :create
      resources :ratings, only: :create
    end
  end

  get '/papers', to: 'papers#index'

  root 'categories#index'
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :category, counter_cache: true
  has_many :comments
  has_many :genres_papers
  has_many :genres, through: :genres_papers
  has_one_attached :image
  has_many :ratings
  belongs_to :student
  has_and_belongs_to_many :paper_read_status,
                          join_table: 'paper_read_status',
                          class_name: 'Student',
                          inverse_of: :paper_read_status

  # Validations
  validates :name  ,length: { maximum: 30 }
  validates :name  ,length: { maximum: 30 }
  validates_presence_of :language
  validate :release_date_not_in_past

  #======================= Scopes ========================================
  scope :between_dates, ->(start_date, end_date) {
    where('release_date <= ? AND release_date >= ?', end_date, start_date)
  }

  #======================== Methods ==============================================================

  def release_date_not_in_past
    return if release_date > Date.today

    errors.add(:release_date, 'invalid release date')
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  load_and_authorize_resource
  skip_before_action :verify_authenticity_token, only: :read_status
  before_action :set_category
  before_action :set_paper, only: %i[ show edit update destroy read_status]

  # GET /papers or /papers.json
  def index
    @end_date = params[:to_date].present? ? params[:to_date] : Time.now
    @start_date = params[:from_date].present? ? params[:from_date] : @end_date - 1.day
    if @category.present?
      @papers = @category.papers.all
    else
      @papers = Paper.all
    end
    @pagy, @papers = pagy(@papers.includes(:category, :comments).between_dates(@start_date, @end_date), items: 10)
  end

  # GET /papers/1 or /papers/1.json
  def show
    @student_comment_rating = StudentCommentRating.new
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers or /papers.json
  def create
    @paper = Paper.new(paper_params)
    @paper.student_id = current_student.id

    respond_to do |format|
      if @paper.save
        format.js
        format.html { redirect_to category_paper_path(@category, @paper), notice: "Paper was successfully created." }
        format.json { render :show, status: :created, location: @paper }
      else
        format.js
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1 or /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to category_paper_path(@category, @paper), notice: "Paper was successfully updated." }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1 or /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to category_papers_url(@category), notice: "Paper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def read_status
    @student = current_student
    unless @paper.paper_read_status_ids.include? @student.id
      @paper.paper_read_status << @student
    end
  end

  private
  def set_category
    @category = Category.find_by(id: params[:category_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_paper
    @paper = @category.papers.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def paper_params
    params.require(:paper).permit(:name, :category_id, :release_date, :language, :image)
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_for [@category, paper], remote: true, html: {id: "paper_form"} do |f| %>
  <div id="error">
    <% if paper.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

        <ul>
        <% paper.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field" hidden>
    <%= f.label :category_id %>
    <%= f.text_field :category_id, value: @category.id %>
  </div>

  <div class="field">
    <%= f.label :release_date %>
    <%= f.datetime_select :release_date %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <br>
    <% if @paper.image.attached? %>
      <%= image_tag @paper.image, style: 'width: 200px;' %>
    <% end %>
    <br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $("#paper_form").submit(function( ) {
    $("#loader_indicator").show();
  });
</script>

app/views/papers/_paper.html.erb
<thead>
<tr>
  <th>Name</th>
  <th>Category</th>
  <th>Release date</th>
  <th>Language</th>
  <th>Read/Unread</th>
  <th>Average Rating</th>
  <th>Comments Count</th>
  <th colspan="3"></th>
</tr>
</thead>
<% @papers.each do |paper| %>
  <tr>
    <td><%= paper.name %></td>
    <td><%= paper.category&.name %></td>
    <td><%= paper.release_date %></td>
    <td><%= paper.language %></td>
    <td><%= current_student.paper_read_status_ids.include?(paper.id) ? "Read" : "Unread" %></td>
    <td><%= paper.average_rating %></td>
    <td><%= paper.comments.size %></td>
    <td><%= link_to 'Show', category_paper_path(paper.category, paper) %></td>
    <% if can? :manage, paper %>
      <td><%= link_to 'Edit', edit_category_paper_path(paper.category, paper) %></td>
      <td><%= link_to 'Destroy', category_paper_path(paper.category, paper), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>

app/views/papers/create.js.erb
<% if @paper.errors.any? %>
  alert("Failed with errors");
  $('#error').append('<%= j render 'layouts/error', model: @paper %>');
<% else %>
  var path = "<%= j category_paper_path(@category, @paper) %>";
  window.location.href = path
<% end %>
$("#loader_indicator").hide();

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', category_paper_path(@category, @paper) %> |
<%= link_to 'Back', category_papers_path(@category) %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <%= form_tag url_for(:controller => 'papers', :action => 'index'), :method => 'get', :id => 'search_form', :class => 'analytics_reports' do %>
    <div class="panel-body">
      <div class="form-horizontal">
        <div class="form-group">
          <div class="row">
            <div class="col-md-3">
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-4 control-label">From:</label>
                <div class="col-sm-8">
                  <%= date_field_tag :from_date, params[:from_date].nil? ? @start_date.to_date : params[:from_date], :id => "from_datepicker", :class => "input-style form-control datepicker" %>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-4 control-label">To:</label>
                <div class="col-sm-8" id="select_transaction_number">
                  <%= date_field_tag :to_date, params[:to_date].nil? ? @end_date.to_date : params[:to_date], :id => "to_datepicker", :class => "input-style form-control datepicker" %>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <div class="form-submit">
                <%= submit_tag "Search", class: 'btn btn1 btn-green', id: 'search' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  <% end %>
  <table class="table table-bordered">

  <tbody>
    <%= render 'paper' %>
  </tbody>
</table>
<%= pagy_nav(@pagy).html_safe %>

<br>
<% if @category.present? %>
  <%= link_to 'New Paper', new_category_paper_path(@category), id: "new_paper_link", remote: true %>
<% end %>

  <script>
    $(document).ready(function () {
      $('.datepicker').datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true,
        todayHighlight: true
      });
    });

    $("#search_form").submit(function (event) {
      var input = $("<input>")
        .attr("type", "hidden")
        .attr("name", "offset").val(new Date().getTimezoneOffset());
      $('#search_form').append($(input));
      return true;
    });

  </script>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', category_papers_path(@category) %>

app/views/papers/new.js.erb
$('#new_paper_link').hide().after('<%= j render 'form', paper: @paper %>');

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>
<p id="read_status"></p>
<p>
  <strong>Name:</strong>
  <%= @paper.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @paper.category.name %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @paper.release_date %>
</p>

<p>
  <strong>Language:</strong>
  <%= @paper.language %>
</p>

<p>
  <strong>Image:</strong>
  <br>
  <% if @paper.image.attached? %>
    <%= image_tag @paper.image, style: 'width: 200px;' %>
  <% end %>
</p>

<%= render 'ratings/index' %>
<%= render 'ratings/form' %>


<p>
  <strong>Genres:</strong>
  <%= @paper.genres.pluck(:name).map(&:humanize).join(", ") %>
</p>

<h3>Add Genre</h3> <%= render 'genres_papers/form', category: @paper.category ,paper: @paper, genres_paper: @genres_paper || GenresPaper.new %>

<h1>Comments</h1>
<%= render 'comments/list', comments: @paper.comments %>

<%= render 'comments/form', category: @paper.category ,paper: @paper, comment: Comment.new %>

<%= link_to 'Edit', edit_category_paper_path(@category, @paper) %> |
<%= link_to 'Back', category_papers_path(@category) %>

<script>
    $("#read_status").ready(function(){
        $.ajax({
            url :'/categories/' + <%= @category.id %> + '/papers/'+ <%= @paper.id %>+'/read',
            type :"POST"
        });
    });
</script>