config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post '/categories/:category_id/papers/:id/read' ,to:'papers#read_status'
  resources :categories do
    resources :papers do
      resources :comments, only: :create do
        resources :student_comment_ratings
      end
      resources :genres_papers, only: :create
      resources :ratings, only: :create
    end
  end

  get '/papers', to: 'papers#index'

  root 'categories#index'
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :papers, dependent: :destroy

  validates_uniqueness_of :name
  validates :description  ,length: { maximum: 250 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :category_code, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container-fluid">
  <div class="col-sm-9">
    <!--Selection Area-->
    <div class="tab-filter panel panel-default">
      <div class="panel-body">
        <%= form_for(category) do |f| %>
          <% if category.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

              <ul>
                <% category.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <div class="row">
              <div class="col-md-6">
                <%= f.label :name, class: "form-label" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>

              <div class="field">
                <div class="col-md-6">
                  <%= f.label :category_code, class: "form-label" %>
                  <%= f.text_field :category_code, class: "form-control" %>
                </div>
              </div>
            </div>
          </div>

          <div class="field">
            <%= f.label :description, class: "form-label" %>
            <%= f.text_area :description, class: "form-control" %>
          </div>
          <br>
          <div class="actions">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>
  <h1>Categories</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category code</th>
      <th>Description</th>
      <th>Total Books</th>
      <th colspan="4">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.category_code %></td>
        <td><%= category.description %></td>
        <td><%= category.papers_count %></td>
        <td><%= link_to 'View papers', category_papers_path(category) %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Category', new_category_path, class: "btn btn-primary" %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>
<div class="container-fluid">
  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path, class: "btn btn-primary" %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Category code:</strong>
  <%= @category.category_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>