config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post '/categories/:category_id/papers/:id/read' ,to:'papers#read_status'
  resources :categories do
    resources :papers do
      resources :comments, only: :create do
        resources :student_comment_ratings
      end
      resources :genres_papers, only: :create
      resources :ratings, only: :create
    end
  end

  get '/papers', to: 'papers#index'

  root 'categories#index'
end

app/models/student_comment_rating.rb
class StudentCommentRating < ApplicationRecord
  belongs_to :comment
  belongs_to :student
end

app/controllers/student_comment_ratings_controller.rb
class StudentCommentRatingsController < ApplicationController
  before_action :set_category_paper_comment
  before_action :set_comment

  def index
    @student_comment_ratings = @comment.student_comment_ratings
  end

  def new

  end

  def edit

  end

  def update

  end

  def create
    @student_comment_rating = current_student.student_comment_ratings.find_or_initialize_by(comment_id: params[:comment_id])
    @student_comment_rating.rating = params[:rating]
    respond_to do |format|
      if @student_comment_rating.save
        format.html { redirect_to category_paper_path(@category, @paper), notice: "student comment rating was successfully created." }
        format.json { redirect_to category_paper_path(@category, @paper), status: :created, location: @user_comment_rating }
      else
        format.html { redirect_to topic_post_path(@topic, @post), notice: "User has already rating that comment ." }
        format.json { render json: @user_comment_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_category_paper_comment
    @category = Category.find_by(id: params[:category_id])
    @paper = @category.papers.find_by(id: params[:paper_id])
  end

  def set_comment
    @comment = @paper.comments.find_by(id: params[:comment_id])
  end

  def student_comment_rating_params
    params.require(:student_comment_rating).permit(:rating, :comment_id)
  end
end

app/views/student_comment_ratings/_form.html.erb
<%= form_with(model: [@topic,@post,@comment,@student_comment_rating])   do |f| %>
  <table>
    <tr>
      <div class="field">
        <td><%= f.radio_button(:rating, "5") %> <%= f.label(:rating, "Very good") %></td>
        <td><%= f.radio_button(:rating, "4") %> <%= f.label(:rating, "good") %></td>
        <td><%= f.radio_button(:rating, "3") %> <%= f.label(:rating,  "normal") %></td>
        <td><%= f.radio_button(:rating, "2") %> <%= f.label(:rating,  "bad") %></td>
        <td><%= f.radio_button(:rating, "1") %> <%= f.label(:rating,  "very bad") %></td>
      </div>
      <td><div class="actions">
        <%= f.submit "rating for the comment",:class => "btn bg-dark text-white" %>
      </div></td>
    </tr>
  </table>
<% end %>

app/views/student_comment_ratings/edit.html.erb
<h1>Editing User Comment Rating</h1>
<br><br>
<h2>
  <%= @comment.comment %>
</h2>
<%= render 'form', student_comment_rating: @student_comment_rating %>

<%= link_to 'Back', topic_posts_path(@topic) %>

app/views/student_comment_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Comment Ratings</h1>

<table>
  <thead>
  <tr>
    <th>User</th>
    <th>Rating</th>
    <th>Comment</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @student_comment_ratings.each do |comment_rating| %>
    <tr>
      <td><%= comment_rating.student.email %></td>
      <td><%= comment_rating.rating %></td>
      <td><%= comment_rating.comment.comment_text %></td>
      <% if can? :manage , comment_rating %>
        <td><%= link_to 'Edit', edit_category_paper_comment_student_comment_rating_path(@category,@paper,@comment,comment_rating) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/student_comment_ratings/new.html.erb
<h1>New User Comment Rating</h1>

<%= render 'form', student_comment_rating: @student_comment_rating %>

<%= link_to 'Back', user_comment_ratings_path %>